# Generated by Django 4.0.5 on 2022-06-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cash',
            field=models.IntegerField(default=20000),
        ),
    ]
