# Generated by Django 4.0.5 on 2022-06-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_portfolio_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stockPrice',
            new_name='priceBought',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='numberOfStocks',
            new_name='stocksOwned',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='bought',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stock',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cashInvested',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bought',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='numberOfStocks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='stockName',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='stockPrice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
