# Generated by Django 4.0.5 on 2022-06-23 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_rename_stockprice_stock_pricebought_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stocksOwned',
            new_name='numberOfStocks',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='priceBought',
            new_name='stockPrice',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='cashInvested',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bought',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='numberOfStocks',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stockName',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stockPrice',
        ),
        migrations.AddField(
            model_name='stock',
            name='bought',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
            preserve_default=False,
        ),
    ]
