# Generated by Django 4.0.5 on 2022-06-23 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_rename_stocksowned_stock_numberofstocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='bought',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='numberOfStocks',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stockPrice',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stock',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cashInvested',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='priceBought',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='stocksOwned',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='bought',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='numberOfStocks',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='stockName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='stockPrice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
